{% set version = "58.1" %}
{% set version_under = version.replace(".", "_") %}

package:
  name: icu
  version: {{ version }}

source:
  fn:  icu4c-{{ version_under }}-src.tgz
  url: http://download.icu-project.org/files/icu4c/{{ version }}/icu4c-{{ version_under }}-src.tgz
  sha256: 0eb46ba3746a9c2092c8ad347a29b1a1b4941144772d13a88667a7b11ea30309
  patches:
    # Include an extra header when using mingw.
    - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch  # [win]
    # Omit lib prefix on libraries.
    - icu-config.patch  # [win]

build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - toolchain
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  files:
    # From http://source.icu-project.org/repos/icu/data/trunk/charset/data/ucm/gb-18030-2000.ucm
    - gb-18030-2000.ucm
    # From ICU's data folder.
    - de.txt
  commands:
    # Libraries
    {% set libs = [
       "libicudata",
       "libicui18n",
       "libicuio",
       "libicutest",
       "libicutu",
       "libicuuc"
     ] %}
    {% for each_lib in libs %}
    - test -f $PREFIX/lib/{{ each_lib }}.a  # [not win]
    - test -f $PREFIX/lib/{{ each_lib }}.{{ version }}.dylib   # [osx]
    - test -f $PREFIX/lib/{{ each_lib }}.so.{{ version }}  # [linux]
    {% endfor %}

    # CLI tests
    - genbrk --help  # [not win]
    - gencfu --help  # [not win]
    - gencnval --help  # [not win]
    - gendict --help  # [not win]
    - icuinfo --help  # [not win]
    - icu-config --help  # [not win]
    - makeconv gb-18030-2000.ucm  # [not win]

    - conda inspect linkages -p $PREFIX icu  # [not win]
    - conda inspect objects -p $PREFIX icu  # [osx]

about:
  home: http://site.icu-project.org/
  license: MIT
  summary: 'International Components for Unicode.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
