travis:
  secure:
    BINSTAR_TOKEN: eQ8E3LfuPwrEhSFtJMp4mmxrIzek2941PvJwaVPNFS+0uSB5cGA3/M0aPOSx6S7klOmSRPgch+9u+sem+7PQCLan9Xt/FSgAPvg8vd0wL8TaLKIyeEDJEtMG0LxKonNoc9eA5TZgUXZgUqaVJnJWGr7NAQXQY1G0/0lI4X1XS6y9XKQqwZZMaVAbR/MkJJtuugaIvmEd0iee5rfCyHlYx5EL0CIMdHSKs5E0uk3PlLzSfeMIzMwURfpCMRmuUTJMTSKYdhl7bJKUBGAldyDY3fasS/INXhk/9hAUSWXMQfMDEEiatzZh0oDE1zSKJnAc2BqqpQsdiAqRZ3UqC4VdSB3thMKgDxCimKlHFEcPMMs2mrKRmaSsviUo5Rqi160J9CEzpvtkqZeQ6xN3jOmNNaTgANsotyC+CC+Z0siy7tdtyd68TA1X5oNk0G0VAwkPKhVdEBdkOYkTPdl5ik2ycvj4h8SSuYpiZkDGO9IahGj1oQJmLyb0GOSAXnA58pxsBZLHK9p9QzIh08peSYa8XV27/GASpY7H9/M21z+cAPFtKEdr3qSZivpDX8667/aqsDhPqtGtuuJcDqQomPB9G6d6aLe5DSmxm0v3s35nG8f3Ame5LpgMTy6LbhKE1y6KDenYDT8AD0rouPhhUPlN28jd+kBTD9wvKVL5Hb4XosI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
